# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# trigger deployment
image: node:12.16.1

pipelines:
  branches:
    production:
      #54.169.178.53
      - step:
          deployment: production
          caches:
            - node
          # size: 2x
          script:
            - yarn install
            - CI=false yarn run build
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: "deploy"
                SERVER: "www.moodah.id"
                COMMAND: "cd app/skywalker/build/ && rm -rf *"
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: "deploy"
                SERVER: "www.moodah.id"
                REMOTE_PATH: "/home/deploy/app/skywalker"
                LOCAL_PATH: "build"
    staging:
      - step:
          deployment: staging
          caches:
            - node
          # size: 2x
          script:
            - yarn install
            - CI=false yarn run build
            - pipe: atlassian/ssh-run:0.1.4
              variables:
                SSH_USER: "deploy"
                SERVER: "skywalker.rubyh.co" 
                COMMAND: "cd app/skywalker/build/ && rm -rf *"
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: "deploy"
                SERVER: "skywalker.rubyh.co"
                REMOTE_PATH: "/home/deploy/app/skywalker"
                LOCAL_PATH: "build"
    
    develop:
      - step:
          deployment: develop
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $HOST_USER
                SERVER: $HOST
                PORT: $SSH_PORT
                MODE: 'script'
                COMMAND: 'dev-deploy-script.sh'